version: '{branch}-0.{build}'
branches:
  only:
  - appveyor
  - release
skip_tags: true
image: Visual Studio 2017
configuration: Release
environment:
  COVERALLS_REPO_TOKEN:
    secure: HocFG7JOlosaliJO/ea9PDMhkeWKV/yzh+Iu2UHbBBGgl724xgG7UiBY8tV90rG6
build_script:
- cmd: >-
    dotnet --version

    dotnet build
test_script:
- cmd: dotnet test WebHdfs.Test\WebHdfs.Test.csproj --test-adapter-path:. --logger:Appveyor
after_test: 
    - packages\OpenCover.4.5.3723\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"nunit-console.exe" -targetdir:"WebHdfs.Test/bin/Release" -targetargs:"WebHdfs.Test.dll" -output:coverage.xml
    - packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
deploy:
- provider: NuGet
  api_key:
    secure: 1La37V7bRU+XrV/GRhP2iqT0VuU1O7RAGZPTtb/Bm5Trqms8iRbIwBW/Y8IQsmVl
  on:
    branch: release