version: '{branch}-0.{build}'
branches:
  only:
  - appveyor
  - release
skip_tags: true
image: Visual Studio 2017
configuration: Release
build_script:
- cmd: >-
    dotnet --version

    dotnet build
test_script:
- cmd: dotnet test WebHdfs.Test\WebHdfs.Test.csproj --test-adapter-path:. --logger:Appveyor
deploy:
- provider: NuGet
  api_key:
    secure: 1La37V7bRU+XrV/GRhP2iqT0VuU1O7RAGZPTtb/Bm5Trqms8iRbIwBW/Y8IQsmVl
  on:
    branch: release

