version: '{branch}-0.{build}'
branches:
  only:
  - appveyor
  - release
skip_tags: true
configuration: Release
build:
  project: WebHdfs.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: 1La37V7bRU+XrV/GRhP2iqT0VuU1O7RAGZPTtb/Bm5Trqms8iRbIwBW/Y8IQsmVl
  on:
    branch: release

